.TH "rapl-set" "1" "2017" "rapl-set" "rapl-set"
.SH "NAME"
.LP
rapl\-set \- set RAPL configurations
.SH "SYNPOSIS"
.LP
\fBrapl\-set\fB [\fIOPTION\fP]...
.SH "DESCRIPTION"
.LP
Sets Intel Running Average Power Limit (RAPL) configurations.
.TP
Since RAPL does not implement all capabilities defined in the powercap interface, only a subset of the options seen powercap-set(1) are available.  Additionally, the \-p and \-z options are different.
.SH "OPTIONS"
.LP
.TP
\fB\-h,\fR \fB\-\-help\fR
Prints out the help screen
.TP
\fB\-p,\fR \fB\-\-package\fR=\fIPACKAGE\fP
The package number to use (0 by default)
.TP
\fB\-z,\fR \fB\-\-subzone=\fR\fISUBZONE\fP
The subzone number to use (none by default)
.TP
\fB\-c,\fR \fB\-\-constraint\fR=\fICONSTRAINT\fP
The constraint number to use (none by default)
.TP
The following is a zone-level argument. You may also specify \-z/\-\-subzone for a subzone:
.TP
\fB\-e,\fR \fB\-\-z\-enabled=1|0\fR
Enable/disable a zone
.TP
The following constraint-level arguments may be used together. The \-c/\-\-constraint option is required. You may also specify \-z/\-\-subzone for a subzone:
.TP
\fB\-l,\fR \fB\-\-c\-power\-limit=UW\fR
Set constraint power limit
.TP
\fB\-s,\fR \fB\-\-c\-time\-window=US\fR
Set constraint time window
.SH "REMARKS"
.LP
Administrative (root) privileges are usually needed to use \fBrapl\-set\fR.
.LP
Subzones are a package's child domains, including power planes.
.LP
Power units: microwatts (uW)
.br
Time units: microseconds (us)
.SH "BUGS"
.LP
The kernel is not guaranteed to accept power limit and time window values exactly as specified.
Values may be rounded due to how they are encoded in Model-Specific Registers.
This rounding error is usually small within normal operating ranges, but can be significant at the extremes.
.LP
Values returned by the kernel, e.g. by rapl\-info(1), sometimes lose accuracy from the actual stored value due to integer rounding.
For example, the kernel may return a time window value of 7812 us, when in fact the actual stored value is 7812.5 us.
Writing back an integer value returned by the kernel may cause unexpected changes to its stored value due to these rounding problems.
.LP
Report bugs upstream at <https://github.com/powercap/powercap>
.SH "FILES"
.nf
\fI/sys/devices/virtual/powercap/intel\-rapl/*\fP
.nf
\fI/sys/class/powercap/intel\-rapl/*\fP
.fi
.SH "AUTHORS"
.nf
Connor Imes <connor.k.imes@gmail.com>
.fi
.SH "SEE ALSO"
.LP
rapl\-info(1), powercap-info(1), powercap-set(1)